name: ai_tasker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.18.1
  animated_bottom_navigation_bar: ^1.2.0
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  google_fonts: ^5.1.0
  email_validator: ^2.1.17
  font_awesome_flutter: ^10.5.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  firebase_database: ^11.3.0
  shared_preferences: ^2.2.0
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  flutter_svg: ^2.0.7
  # connectivity: ^3.0.6
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/
